### ISSUE TITLE
packrat issues with dev branch

### ISSUE THREAD

**Issue by fawda123** [niklasvm/shiny-strava#8]
Hey Nick, so I'm having some serious packrat woes with the dev branch.  Here's what I see when I open the project:

![image](https://user-images.githubusercontent.com/3086881/43967179-ab32788c-9c78-11e8-9a21-ff9230c9548c.png)

Then when I try to source any of the app files, I get this popup:
![image](https://user-images.githubusercontent.com/3086881/43967245-d1cae2fe-9c78-11e8-9353-d9607fb95812.png)

Okay, so then when I try to install the missing packages to the local lib, I get this: 
![image](https://user-images.githubusercontent.com/3086881/43967291-ebf28ce0-9c78-11e8-9438-334c3e7e299c.png)

I'm guessing it might be something with how the packrat project is setup, any ideas?

**Comment by niklasvm** [comment]
That's quite a strange set of error messages. Which version of R are you using? You may also need RTools to install packages from source.

I have successfully installed all the packages via packrat on my windows PC and in a linux docker container.

You can always comment out the the line in ```.Rprofile``` that loads packrat. That should at least be temporary solution.

**Comment by fawda123** [comment]
Okay, I updated my version of R and was able to get all the dependencies up and running in a packrat project.  I'm thinking it might be better not to use packrat with the repo.  I eventually got everything working but I suspect others will have challenges with it too.  I don't know, I see good reasons for using both approaches.  What do you think? 

I'll check out the other features in #6 soon.
